version: 2
jobs:
  build:
    docker:
      - image: af01/pocolog2msgpack-ci:latest
    steps:
      - checkout
      - run:
          name: Build
          command: ./build_tools/circleci/build.sh
      - run:
          name: Test
          command: ./build_tools/circleci/test.sh

